name: tots_stacked_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  dartz: ^0.10.1
  dio: ^5.7.0
  dotted_border: ^2.1.0
  encrypt: ^5.0.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  stacked: ^3.4.0
  stacked_services: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.5
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.1
  stacked_generator: ^1.3.3

flutter_launcher_icons:
  android: "tots_icons"
  ios: false
  image_path: "assets/images/logo_app.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/logo_app.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"

flutter:
  uses-material-design: true
  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans-VariableFont_opsz,wght.ttf

  assets:
    - assets/images/
